global:
  imagePullSecrets: [] # private registry 접근시 필요한 imagepullSecret

kubernetes:
  host: https://kubernetes.default

reloader:
  isArgoRollouts: true # Enable Argo Rollouts. Valid value are either true or false
  isOpenshift: false # Enable OpenShift DeploymentConfigs. Valid value are either true or false
  ignoreSecrets: false # To ignore secrets. Valid value are either true or false
  ignoreConfigMaps: false # To ignore configMaps. Valid value are either true or false
  reloadOnCreate: true # Enable reload on create events. Valid value are either true or false
  reloadStrategy: default # Set to default, env-vars or annotations
  ignoreNamespaces: "" # Comma separated list of namespaces to ignore
  logFormat: "" #json
  watchGlobally: true
  readOnlyRootFileSystem: false
  legacy:
    rbac: false
  matchLabels: {}
  deployment:
    replicas: 1
    nodeSelector:
    affinity: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
    containerSecurityContext: {}
    tolerations: []
    annotations: {}
    labels:
      provider: stakater
      group: com.stakater.platform
      version: v0.0.117
    image:
      name: stakater/reloader
      tag: v0.0.117
      pullPolicy: IfNotPresent
    # Support for extra environment variables.
    env:
      # Open supports Key value pair as environment variables.
      open:
      # secret supports Key value pair as environment variables. It gets the values based on keys from default reloader secret if any.
      secret:
      # field supports Key value pair as environment variables. It gets the values from other fields of pod.
      field:

    livenessProbe: {}
    readinessProbe: {}
    resources: {}
    pod:
      annotations: {}
    priorityClassName: ""

  service: {}
  rbac:
    enabled: true
    labels: {}
  serviceAccount:
    create: true
    labels: {}
    annotations: {}
    name:
  custom_annotations: {}

  serviceMonitor:
    enabled: false

  podMonitor:
    enabled: false

